### ISSUE TITLE
Crash in edit dialog for CalDAV event with attendees

### ISSUE THREAD

**Issue by min7-i** [FossifyOrg/Calendar#34]
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x] I have read the FAQ and my problem isn't listed.
 - [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x] This issue contains only one bug.
 - [x] I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
For a CalDAV event with attendees the app crashes in the edit dialog when opening the time zone selector or when switching back and forth between the calendar app and other apps.

**To Reproduce**
1. Make sure that "CalDAV sync" and "Allow changing event time zones" are checked in settings.
2. Open the edit dialog for a CalDAV event that has attendees.
3. Tap on the time zone.
4. The app crashes.

**Expected behavior**
The time zone list is displayed without any crash happening. / Switching between the calendar app and other apps doesn't cause any crashes.

**Screenshots**
N/A (see crash log below)

**Device info (please complete the following information):**
 - Model: Google Pixel 6a
 - OS: Android 14 (GrapheneOS)
 - Version: 1.0.2

**Additional context**
<details>
<summary>crash log</summary>

```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.240105.002/2024010400:user/release-keys
package: org.fossify.calendar:3
process: org.fossify.calendar
processUptime: 6210 + 187 ms
installer: com.android.packageinstaller

android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = org.fossify.calendar.models.Event)
	at android.os.Parcel.writeSerializable(Parcel.java:2799)
	at android.os.Parcel.writeValue(Parcel.java:2565)
	at android.os.Parcel.writeValue(Parcel.java:2364)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1919)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1956)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.io.NotSerializableException: org.fossify.calendar.models.Attendee
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:873)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1079)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1568)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2794)
	... 16 more

```

</details>

**Comment by jguegel** [comment]
didnt find this issue by searching for timezone... sorry for duplicate

**Comment by naveensingh** [comment]
We all do it: https://github.com/FossifyOrg/Calendar/issues/584
